version: '3'
services:


    # Cells image with two named volumes for the static and for the data
    #https://hub.docker.com/r/pydio/cells
    cells:
        image: pydio/cells:2.0.0
        restart: always
        volumes:
        #- "./volume/data:/var/cells/data"
          - "data:/var/cells/data"
          - "cellsdir:/var/cells"
        ports: ["8080:8080"]
        environment:
          - CELLS_BIND=localhost:8080
          - CELLS_EXTERNAL=https://${ADDR}:${PORT}

    # MySQL image with a default database cells and a dedicated user pydio
    mysql:
         image: mysql:5.7
         restart: always
         environment:
             MYSQL_ROOT_PASSWORD: ${PWD_ROOT}
             MYSQL_DATABASE: cells
             MYSQL_USER: pydio
             MYSQL_PASSWORD: ${PWD_PYDIO}
         command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
         ports: ["3306:3306"]
         volumes:
           - "mysqldir:/var/lib/mysql"

volumes:
    data: {}
    cellsdir: {}
    mysqldir: {}
