version: '3'
services:

    mongodb:
        image: registry.csjt.redejt/dockerhub/library/mongo:4.2
        ports: ["27017:27017"]
        # If you need to connect to your db from outside this container
        #network_mode: host
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rieGh1Ah7Thahch1
        volumes:
          - "./data/db:/data/db"
          - "./data/configdb:/data/configdb"
        #  - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
        #command:
        #  - mongod
          #- --auth
