version: '3'
services:

    mongodb:
        image: registry.csjt.redejt/dockerhub/library/mongo:5.0.10
        ports: ["8082:8081"]
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rieGh1Ah7Thahch1
        volumes:
          - ./data:/data/db
