version: '3'
services:

    mongodb:
        image: library/mongo:4.2
        ports: ["27017:27017"]
        # If you need to connect to your db from outside this container
        #network_mode: host
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PWD}
        #user: 'mongodb'
        volumes:
          - mongodata:/data/db

volumes:
  mongodata:
    external: true
