version: '3'
services:

    mongodb:
        image: library/mongo:5.0.10
        ports: ["27017:27017"]
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rieGh1Ah7Thahch1
        volumes:
          - ./data:/data:rw
