version: '3.4'

services:

  kibana:
    image: kibana:7.5.2
    container_name: "kibana"
    ports:
      - ${KIBANAIP}:80:5601
    environment:
      SERVER_NAME: "Kibana"
      ELASTICSEARCH_HOSTS: "http://${ESIP}:9200"
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: ${KIBANAPASS}
